appVersion: v1
kind: Service
metadata:
  name: php
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 9080
      
---

appVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 18080
      
---

appVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
